### ISSUE TITLE
Targetability Status

### ISSUE THREAD

**Issue by leostera** [AbstractMachinesLab/lam#7]
One of the goals of LAM is to be easy to target.

This means that we should provide tools to work with the bytecode, inspect it,  and debug it. Ideally both in binary and text format, and converting between them quickly.

### Bytecode

- [ ] Define a text format -- leaning towards S-expressions, like WebAssembly's .wat
- [ ] Define a binary format -- open to ideas

### Tools

- [ ] `lam validate` -- can validate bytecode in text and binary format
- [ ] `lam text-to-bin` and `lam bin-to-text` -- translate bytecode between text and binary format
- [ ] `lam inspect` -- meta information about the provided bytecode
- [ ] `lam compile` -- should emit DWARF debug symbols by default, but drop 'em with a `--release` flag
- [ ] `lam debug` -- should start a step-debugger for a LAM program
