### ISSUE TITLE
WebAssembly and Native Runtime Support

### ISSUE THREAD

**Issue by leostera** [AbstractMachinesLab/lam#8]
Will use this issue tro track the broad strokes of standard APIs for LAM across runtimes.

Ideally we'd have a feature parity across platform but that can't be guaranteed so at least we should have a consistent core and platform specific extensions.

## WebAssembly (Web)

- [ ] File System (powered by [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) or [vfs](https://crates.io/crates/vfs))
- [ ] Network (powered by [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [WebSockets API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API))
- [ ] Logging (powered by [Console API](https://developer.mozilla.org/en-US/docs/Web/API/Console_API))
- [ ] Time (powered by [Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API))
- [ ] DOM API
- [ ] CSSOM API
- [ ] WebGL API
- [ ] Canvas API

## WebAssembly (Server-side)

- [ ] File System
- [ ] Network
- [ ] Logging
- [ ] Time

## Native

- [ ] File System
- [ ] Network
- [ ] Logging
- [ ] Time
